/* 
 * apiPredictPurchasePrice
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InputParameters
    /// </summary>
    [DataContract]
    public partial class InputParameters :  IEquatable<InputParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InputParameters" /> class.
        /// </summary>
        /// <param name="Age">numeric.</param>
        /// <param name="Gender">character.</param>
        /// <param name="ProductSelected">character.</param>
        public InputParameters(decimal? Age = default(decimal?), string Gender = default(string), string ProductSelected = default(string))
        {
            this.Age = Age;
            this.Gender = Gender;
            this.ProductSelected = ProductSelected;
        }
        
        /// <summary>
        /// numeric
        /// </summary>
        /// <value>numeric</value>
        [DataMember(Name="age", EmitDefaultValue=false)]
        public decimal? Age { get; set; }

        /// <summary>
        /// character
        /// </summary>
        /// <value>character</value>
        [DataMember(Name="gender", EmitDefaultValue=false)]
        public string Gender { get; set; }

        /// <summary>
        /// character
        /// </summary>
        /// <value>character</value>
        [DataMember(Name="productSelected", EmitDefaultValue=false)]
        public string ProductSelected { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InputParameters {\n");
            sb.Append("  Age: ").Append(Age).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("  ProductSelected: ").Append(ProductSelected).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InputParameters);
        }

        /// <summary>
        /// Returns true if InputParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of InputParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InputParameters other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Age == other.Age ||
                    this.Age != null &&
                    this.Age.Equals(other.Age)
                ) && 
                (
                    this.Gender == other.Gender ||
                    this.Gender != null &&
                    this.Gender.Equals(other.Gender)
                ) && 
                (
                    this.ProductSelected == other.ProductSelected ||
                    this.ProductSelected != null &&
                    this.ProductSelected.Equals(other.ProductSelected)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Age != null)
                    hash = hash * 59 + this.Age.GetHashCode();
                if (this.Gender != null)
                    hash = hash * 59 + this.Gender.GetHashCode();
                if (this.ProductSelected != null)
                    hash = hash * 59 + this.ProductSelected.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
